name: flutter_form_generator
description: Provides Dart Build System builders for generating Flutter Forms
version: 0.0.1
homepage: https://bitbucket.org/IndeDude/form_generator

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  dart_style: ^2.2.3
 
dev_dependencies:
  build: ^2.2.1
  source_gen:
  flutter_form_annotations:
    path: ../flutter_form_annotations/
  build_test:
  build_runner:
  test: ^1.0.0
