name: form_gen
description: Provides  [Dart Build System] builder for handling Flutter Form generation for Flutter models.The builders generate code when they find *classes* and *members* annotated with classes defined in package flutter_form_annotations.

version: 0.0.1-dev-01b
homepage: https://github.com/SudhindraAnegondhi/form_gen.git

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  analyzer: ^3.4.1
  build: ^2.2.1
  dart_style: ^2.2.3
  flutter_form_annotations: ^0.0.1-dev-01a
  source_gen: ^1.2.2
 
dev_dependencies:
  
  build_test:
  build_runner:
  test: ^1.0.0
