name: form_gen
description: Form Generator for flutter
version: 0.0.1
homepage: https://github.com/SudhindraAnegondhi/form_gen.git

environment:
  sdk: ">=2.17.6 <3.0.0"
 

dependencies:
   dart_style: ^2.2.3

dev_dependencies:
  build: ^2.2.1
  source_gen:
  build_test:
  build_runner:
  test: ^1.0.0

